#pragma once

#include"Define.h"

class ItemInfo
{
public:
	enum struct ItemType
	{
		USE,
		SWORD,
		ROD,
		HELMET,
		ARMOR,
		CAP,
		ROBE,
		ACCESSORY,
		KEY,
		INGREDIENT
	};
	enum struct ItemOption
	{
		HP_HEAL_VALUE,
		MP_HEAL_VALUE,
		CURE_ALL_CONDITIONERROR,
		REVIVAL,
		HEAL_MAX,
		ATK_UP_PERCENT,
		ATK_UP_TIME,
		INT_UP_PERCENT,
		INT_UP_TIME,
		DEF_UP_PERCENT,
		DEF_UP_TIME,
		RES_UP_PERCENT,
		RES_UP_TIME,
		HP_UP_PERCENT,
		HP_UP_TIME,
		MP_UP_PERCENT,
		MP_UP_TIME,
		STOP_TIME,
		REDUCE_STIFF_AMOUNT,
		REDUCE_STIFF_PERCENT,
		REDUCE_STIFF_TIME,
		REDUCE_PAY_MP_AMOUNT,
		REDUCE_PAY_MP_PERCENT,
		REDUCE_PAY_MP_TIME,
		AUTO_HEEL_HP_AMOUNT,
		AUTO_HEEL_HP_PERCENT,
		AUTO_HEEL_MP_AMOUNT,
		AUTO_HEEL_MP_PERCENT,
		PREVENT_POISON,
		PREVENT_SLEEPING,
		PREVENT_STAN,
		HALF_DEFENCE,
		HEEL_HP_WHEN_ATTACK,
		HEEL_MP_WHEN_ATTACK,
		RAISE_NORMAL_ATTACK_DAMAGE_PERCENT,
		REDUCE_NORMAL_ATTACK_DAMAGE_PERCENT,
		RAISE_SKILL_DAMAGE_PERCENT,
		REDUCE_SKILL_DAMAGE_PERCENT,
		REDUCE_DAMAGE_WHEN_STIFFING_PERCENT,
		RAISE_DAMAGE_TO_PREACTION_PERCENT,
		RAISE_DAMAGE_WHEN_MAX_SP_PERCENT,
		AUTO_DECREASE_SP_AMOUNT,
		RAISE_DAMAGE_WHEN_UNDER_30_PERCENT,
		MOVE_SPEED_RATE,
		RAISE_EXPERIENCE,
		RAISE_MONEY,
		SIZE
	};
public:
	string name;
	ItemType type;
	int graphNum;
	string description;
	int HP;
	int SP;
	int ATK;
	int DEF;
	int INT;
	int RES;
	array<double, (int)ItemOption::SIZE> option;
	int buyMoney;
	int sellMoney;
	int maxHoldNum;
};